baseurl: /swift-macos

collections_dir: sections

collections:
  getting_started:
    output: true
    permalink: /:title
  types:
    output: true
    permalink: /:title
  command_line:
    output: true
    permalink: /:title
  file_system:
    output: true
    permalink: /:title

exclude: [README.md, Gemfile]
