baseurl: /swift-macos

collections:
  sections:
    output: true
    permalink: /:title

defaults:
  - scope:
      path: ""
      type: "sections"
    values:
      layout: "section"

exclude: [Gemfile]